#!/bin/bash
# Guide to remove all Screenpipe privacy settings

echo "🔒 REMOVE SCREENPIPE FROM PRIVACY SETTINGS"
echo "=========================================="
echo ""
echo "⚠️  This MUST be done manually - macOS doesn't allow automated removal"
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  SCREEN RECORDING"
echo "   • Open System Preferences → Security & Privacy → Screen Recording"
echo "   • Look for ALL entries containing 'screenpipe' or 'screenpipe-app'"
echo "   • Click the lock 🔒 to unlock (enter password)"
echo "   • Select each screenpipe entry and click the - button"
echo "   • Common entries:"
echo "     - screenpipe"
echo "     - screenpipe-app"
echo "     - screenpipe (multiple versions)"
echo "     - target/release/screenpipe-app"
echo "     - target/debug/screenpipe-app"
echo ""
echo "2️⃣  MICROPHONE"
echo "   • Open System Preferences → Security & Privacy → Microphone"
echo "   • Click the lock 🔒 to unlock"
echo "   • Remove ALL screenpipe entries"
echo ""
echo "3️⃣  ACCESSIBILITY (if present)"
echo "   • Open System Preferences → Security & Privacy → Accessibility"
echo "   • Click the lock 🔒 to unlock"
echo "   • Remove any screenpipe entries"
echo ""
echo "4️⃣  FULL DISK ACCESS (if present)"
echo "   • Open System Preferences → Security & Privacy → Full Disk Access"
echo "   • Click the lock 🔒 to unlock"
echo "   • Remove any screenpipe entries"
echo ""
echo "5️⃣  LOGIN ITEMS"
echo "   • Open System Preferences → Users & Groups → Login Items"
echo "   • Remove any screenpipe entries"
echo ""
echo "📋 Quick Access:"
echo "   Press: System Preferences → Security & Privacy"
echo "   Or run: open x-apple.systempreferences:com.apple.preference.security"
echo ""
echo "✅ After removing all entries, you're ready for a fresh install!"
echo ""
echo "💡 TIP: Look carefully - there might be 10-20 duplicate entries!"
echo ""

# Open System Preferences to the right location
read -p "Open Security & Privacy settings now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    open "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"
    echo ""
    echo "✅ Opened Screen Recording settings"
    echo "   After cleaning Screen Recording, manually navigate to Microphone tab"
fi
